[package]
name = "euler"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "factors"
harness = false

[dependencies]
itertools = "0.10.3"
owo-colors = "3.2.0"

[dev-dependencies]
proptest = "1.0.0"
criterion = "0.3"
